id: P006932
initial_creation_type: ocr
source_metadata:
  id: bdr:W17636
  title: ཚད་མའི་སྙིང་པོ་བསྡུས་གྲྭའི་རྣམ་གཞག
  author: ''
  volumes:
    30fe849320f94a9db960010765c99b45:
      image_group_id: I1KG10513
      title: ''
      volume_number: 1
      total_pages: 334
ebook_metadata:
  title: ཚད་མའི་སྙིང་པོ་བསྡུས་གྲྭའི་རྣམ་གཞག
  author: ''
  sku: P006932
  cover: cover.jpg
  layers: []
